ACS-4813 Migrate to GHA
Alfresco/alfresco-keycloak-theme pull request #16
Opened 2023-03-16 13:20 UTC by aonych

2023-03-16 13:38 UTC, dsibilio requested changes

2023-03-16 13:38 UTC, dsibilio commented on .github/workflows/ci.yml
> +name: Alfresco Keycloak Theme
Missing conventional `CI` at the end of the name.

2023-03-16 13:38 UTC, dsibilio commented on .github/workflows/ci.yml
> +    types: [created]
People seem to be suggesting that `published`, instead of `created` acts more consistently: https://stackoverflow.com/questions/59319281/github-action-different-between-release-created-and-published.

2023-03-16 13:44 UTC, aonych commented on .github/workflows/ci.yml
> +        run: gh release upload ${{  github.ref_name }}" alfresco-keycloak-theme-${{ github.ref_name }}".zip
I've tried several solutions and it's just leftovers. Thanks!

2023-03-16 14:01 UTC, dsibilio requested changes

2023-03-16 14:01 UTC, dsibilio commented on .github/workflows/ci.yml
> +          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
This secret does not exist.

2023-03-17 12:25 UTC, damianujma approved these changes

2023-03-17 15:49 UTC, mikolajbrzezinski approved these changes

2023-03-20 08:28 UTC, gionn approved these changes

2023-03-20 11:25 UTC, dsibilio approved these changes
LGTM. Please let's test the release process and verify if the release job needs additional permissions.

2023-03-23 10:02 UTC, dsibilio approved these changes
LGTM. Please let's delete the test releases and tags we made.

2023-03-23 10:22 UTC, merged